### ISSUE TITLE
Deleting a pinned link not working on home page ini Firefox

### ISSUE THREAD

**Issue by Ezyweb-uk** [MarceauKa/shaark#81] opened 2020-07-08 17:11 UTC
I tried to delete a pinned link on the home page. After clicking the More button, then Delete, I can see 'Confirm' shows momentarily but then dissappears and nothing else happens.

Nice modern looking system!

**Comment by wyred** [comment] 2020-07-09 02:41
You have to quickly click again when the "Confirm" word shows up, in order for it to be deleted.

Not sure if this is intended behaviour in order to prevent accidental deletes.

**Comment by Ezyweb-uk** [comment] 2020-07-09 07:38
The timeslot is too short on my Firefox, it's microseconds. You're right it is possible after a few attempts. An improvement would be a much longer time period to show the confirm option, and for the screen to refresh to remove the item.

**Comment by MarceauKa** [comment] 2020-09-08 14:11
Fixed in [1.2.43](https://github.com/MarceauKa/shaark/releases/tag/1.2.43)

**Closed by MarceauKa** 2020-09-08 14:11 UTC
Labels: bug
